name: Generate Static & Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # 每 30 分钟运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ensure logs directory exists
        run: mkdir -p logs

      - name: Run crawler
        run: python new_crawler.py

      - name: Archive output folder
        uses: actions/upload-artifact@v4
        with:
          name: site-static
          path: output

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download output artifact
        uses: actions/download-artifact@v4
        with:
          name: site-static
          path: site

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 142.171.235.178 >> ~/.ssh/known_hosts

      - name: Deploy to aapanel server
        run: |
          scp -r site/* root@142.171.235.178:/www/wwwroot/freecomic.website/
