name: Generate & Deploy Site

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # 每 30 分钟自动运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r freecomic-site/requirements.txt

      - name: Run crawler
        run: python freecomic-site/new_crawler.py

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-static
          path: freecomic-site/output/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site-static
          path: site

      - name: Deploy to Server via SCP
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -r site/* root@142.171.235.178:/www/wwwroot/freecomic.website/
