name: Generate Static & Deploy

on:
  workflow_dispatch:        # 手动触发支持
  schedule:
    - cron: '0 */3 * * *'   # 每3小时自动运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure required folders
        run: |
          mkdir -p logs output news images css database

      - name: Run crawler once
        run: python new_crawler.py

      - name: Archive site output
        uses: actions/upload-artifact@v4
        with:
          name: site-static
          path: output

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site-static
          path: site

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 142.171.235.178 >> ~/.ssh/known_hosts

      - name: Deploy to Server via SCP
        run: |
          scp -o StrictHostKeyChecking=no -r site/* root@142.171.235.178:/www/wwwroot/freecomic.website/
